### ISSUE TITLE
RuntimeException: Assertion Failed: SpotXActivity presented without a controller

### ISSUE THREAD

**Issue by mhelder** [spotxmobile/spotx-sdk-android#3]
We're seeing the following crash on roughly 1% of our daily user base, consisting of about ~3000 unique users (daily), resulting in 25~40 crashes logged to Crashlytics per day. Specifically, we're using `InterstitialPresentationController` to display a pre-roll video before some (video) content can be viewed by the user. 

_(Note: analysis below is based on what I can determine from the decompiled code, using Android Studio)_

The origin of the error is easily traced to `SpotXActivity.onCreate()`, which has an assert statement that throws a plain `RuntimeException` when the `SpotXAdGroup` polled from the `Deque<>` (unexpectedly) returned null.

Looking at the static method `InterstitialPresentationController.show()` that we're calling to initiate the pre-roll, it effectively has the same assert statement. The 2nd line appears to be where the `Deque` in `SpotXActivity` is supplied with the later-to-be-polled `SpotXAdGroup`.

    Assert.test(adGroup != null, "adGroup must not be null");
    SpotXActivity.ads.add(adGroup);
    ctx.startActivity(new Intent(ctx, SpotXActivity.class));

So, for some reason, it appears that sometimes the `Deque<>` with the `SpotXAdGroup` is cleared out _after_ starting the `SpotXActivity` and _before_ its `onCreate()`. Unfortunately we have not been able to reproduce this on any of our test devices. We've already triple checked and confirmed that we're calling `InterstitialPresentationController.show()` from the main thread, and there haven't been any crashes on the assert in that method (meaning that `SpotXAdGroup != null` everytime the method is invoked from our app's code). We are starting to run out of leads to chase. Any ideas/suggestions?

Crash happens across the board of Android versions supported by our app: API level 16+. Target & compile SDK versions: 24. Feel free to request more details if needed.

Full stack trace:

    Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.package.name/com.spotxchange.v3.view.SpotXActivity}: java.lang.RuntimeException: Assertion Failed: SpotXActivity presented without a controller
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
        at android.app.ActivityThread.access$900(ActivityThread.java:172)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:146)
        at android.app.ActivityThread.main(ActivityThread.java:5694)
        at java.lang.reflect.Method.invokeNative(Method.java)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
        at dalvik.system.NativeStart.main(NativeStart.java)
    Caused by java.lang.RuntimeException: Assertion Failed: SpotXActivity presented without a controller
        at com.spotxchange.internal.util.Assert.test(SourceFile:9)
        at com.spotxchange.v3.view.SpotXActivity.onCreate(SourceFile:40)
        at android.app.Activity.performCreate(Activity.java:5541)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
        at android.app.ActivityThread.access$900(ActivityThread.java:172)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:146)
        at android.app.ActivityThread.main(ActivityThread.java:5694)
        at java.lang.reflect.Method.invokeNative(Method.java)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
        at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by lcniles** [comment]
Thanks, @mhelder, for bringing this to our attention. What appears to be happening is as follows. 

1. Your app is correctly calling `InterstitialPresentationController.show(),` which queues the specified ad group and triggers and `Intent` to present a `SpotXActivity.`

2. The `SpotXActivity` dequeues the ad group and begins playback. At this point the user sends your app to the background.

3. After some time, the Android OS needs to increase available memory and reaps the `SpotXActivity` instance.

4. Later, when your app is brought back to the foreground, Android attempts to reconstitute that same `SpotXActivity`. At this point the queue is empty and the assertion fails.

We are immediately addressing this issue and will be releasing version 3.1.1 today (10 Oct 2016).

**Comment by lcniles** [comment]
Hi, @mhelder, I'm just updating this thread: we have released v3.1.1 to address this issue. I'm marking this as closed, but feel free to reopen if the issue persists.

Cheers

**Comment by mhelder** [comment]
Thanks for the quick reply, @lcniles. What you're describing makes absolute sense with respect to the strack trace. Should've thought of that scenario... Anyways, cheers for the update. From the look of it, the throwing assert is removed from the `SpotXActivity` and instead the activity is finished if the `SpotXAdGroup == null` (or: was flushed from memory). Any other (related) changes we should be aware of?

We'll probably roll out an update of our app with version 3.1.1 of the SpotX SDK sometime this week. I'm expecting this particular issue to no longer persist, but will give a ping if it does.

**Comment by lcniles** [comment]
The 3.1.1 release was mainly some internal efforts to do things better. The public-facing changes are the this bug here and support for Brightcove when using Google's ExoPlayer. Release notes are here: http://spotxmobile.github.io/android/release-notes/
